<?php 
if (defined('RUNNING_FROM_ROOT')) {
  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" href="<?php echo $this->basepath();?>/extjs/resources/css/ext-all.css"/>
<script type="text/javascript" src="<?php echo $this->basepath();?>/extjs/ext-debug.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath();?>/user/appLogin.js"></script>
<link rel="stylesheet" href="<?php echo $this->basepath();?>/user/app/resources/style.css"/>
<title>Sistema de Gerenciamento de Chamados - Prefeitura Municipal de Santa Helena de Goiás </title>
</head>
<body>
</body>
</html>